version: "3.9"
services:
  distance-calculator:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - USER_API_URL=https://bpdts-test-app.herokuapp.com